"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { Bell, CalendarClock, Check, CircleDollarSign, ExternalLink, Gauge, Luggage, Sparkles } from "lucide-react";
import type { ControlCentreWorkspace } from "@/lib/control-centre/repository";

function money(value: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
function Card({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[.045] p-4 sm:p-5"><h2 className="mb-4 flex items-center gap-2 text-base font-bold">{icon}{title}</h2>{children}</section>; }

export default function TripWorkspaceClient({ initial }: { initial: ControlCentreWorkspace }) {
  const [data, setData] = useState(initial);
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const days = Math.max(0, Math.ceil((new Date(data.trip.startDate).getTime() - Date.now()) / 86_400_000));
  const recommendations = useMemo(() => data.readiness.missing.map((item) => ({ key: item, text: ({ transport: "Book your main transport", accommodation: "Confirm your accommodation", activities: "Confirm at least one key activity", documents: "Complete passport and visa checks", packing: "Finish your essential packing items", insurance: "Confirm travel insurance", connectivity: "Arrange an eSIM or roaming", budget: "Set a realistic trip budget", airportTransfers: "Arrange your airport transfer" } as Record<string,string>)[item] || `Complete ${item}` })), [data.readiness.missing]);

  async function mutate(payload: Record<string, unknown>, key: string) {
    setBusy(key); setNotice(null);
    const response = await fetch("/api/control-centre/trip", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, planId: data.trip.id }) });
    const result = await response.json().catch(() => null); setBusy(null);
    if (!response.ok || !result?.workspace) { setNotice("That update could not be saved. Please try again."); return; }
    setData(result.workspace); setNotice("Saved to your trip.");
  }

  async function addReminder(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const when = new Date(String(form.get("when")));
    setBusy("reminder");
    const response = await fetch("/api/profile/reminders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), tripName: data.trip.title, reminderType: "trip", reminderDate: when.toISOString(), metadata: { planId: data.trip.id } }) });
    setBusy(null); setNotice(response.ok ? "Reminder saved in your profile." : "The reminder could not be saved."); if (response.ok) event.currentTarget.reset();
  }

  return <main className="min-h-screen bg-[#071019] px-3 py-5 text-white sm:px-6 lg:px-10">
    <div className="mx-auto max-w-7xl">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href="/profile/control-centre" className="text-xs text-[#ffae64]">Back to Control Centre</Link><h1 className="mt-2 font-serif text-3xl sm:text-4xl">{data.trip.title}</h1><p className="mt-1 text-sm text-white/55">{data.trip.destination}</p></div><div className="rounded-2xl border border-[#ff7a00]/35 bg-[#ff7a00]/10 px-5 py-3 text-center"><strong className="block text-2xl text-[#ff9a3c]">{days}</strong><span className="text-[11px] text-white/60">days to go</span></div></div>
      {notice ? <div className="mb-4 rounded-xl border border-[#ff7a00]/30 bg-[#ff7a00]/10 px-4 py-3 text-sm text-[#ffc38d]">{notice}</div> : null}
      <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><Gauge className="h-5 w-5 text-[#ff7a00]"/><strong className="mt-3 block text-3xl">{data.readiness.score}%</strong><span className="text-xs text-white/50">Trip Readiness Score</span></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><CircleDollarSign className="h-5 w-5 text-[#ff7a00]"/><strong className="mt-3 block text-xl">{money(data.budget.remaining, data.budget.currency)}</strong><span className="text-xs text-white/50">Budget remaining</span></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><Sparkles className="h-5 w-5 text-[#ff7a00]"/><strong className="mt-3 block text-sm">{data.readiness.nextAction}</strong><span className="text-xs text-white/50">Best next action</span></div></div>
      <div className="grid gap-5 xl:grid-cols-2">
        <Card title="Smart booking checklist" icon={<Check className="h-5 w-5 text-[#ff7a00]"/>}><div className="space-y-3">{data.items.length ? data.items.map((item)=><div key={item.id} className="rounded-xl border border-white/10 bg-black/15 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-sm">{item.title}</strong><div className="mt-1 flex flex-wrap gap-2 text-[10px]"><span className="rounded bg-white/8 px-2 py-1">{item.kind}</span><span className="rounded bg-sky-400/10 px-2 py-1 text-sky-300">{item.priceLabel}</span></div>{item.price != null && item.currency ? <p className="mt-2 text-xs text-white/55">{money(item.price,item.currency)} · prices can change until provider confirmation</p>:<p className="mt-2 text-xs text-white/45">Final price is confirmed on the provider site.</p>}</div><div className="flex gap-2">{item.hasBookingLink?<a href={`/api/affiliate/redirect?customerPlanId=${data.trip.id}&customerItemId=${item.id}`} target="_blank" rel="noopener noreferrer sponsored" className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-[#ff7a00]/45 px-3 text-xs font-bold text-[#ffae64]">Book <ExternalLink className="h-3 w-3"/></a>:null}<button disabled={busy===item.id||item.bookingStatus.includes("CONFIRMED")} onClick={()=>mutate({action:"confirm-booking",itemId:item.id},item.id)} className="min-h-10 rounded-lg bg-[#ff7a00] px-3 text-xs font-bold disabled:opacity-50">{item.bookingStatus.includes("CONFIRMED")?"Confirmed":"I booked it"}</button></div></div></div>):<p className="text-sm text-white/50">Trip items will appear here when the itinerary is saved.</p>}</div></Card>
        <Card title="Missing-item recommendations" icon={<Sparkles className="h-5 w-5 text-[#ff7a00]"/>}><div className="space-y-2">{recommendations.length?recommendations.map((item)=><div key={item.key} className="flex items-center gap-3 rounded-xl border border-white/8 p-3 text-sm"><span className="h-2 w-2 rounded-full bg-[#ff7a00]"/>{item.text}</div>):<p className="text-sm text-emerald-300">Everything essential is covered.</p>}</div></Card>
        <Card title="Trip readiness checklist" icon={<Gauge className="h-5 w-5 text-[#ff7a00]"/>}><div className="space-y-2">{data.tasks.map((task)=><label key={task.id} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-white/8 px-3 text-sm"><input type="checkbox" checked={task.status==="COMPLETED"} disabled={busy===task.id} onChange={(e)=>mutate({action:"toggle-task",id:task.id,completed:e.target.checked},task.id)} className="h-4 w-4 accent-[#ff7a00]"/><span className={task.status==="COMPLETED"?"text-white/40 line-through":""}>{task.title}</span>{task.critical?<span className="ml-auto text-[9px] font-bold uppercase text-[#ffae64]">Essential</span>:null}</label>)}</div></Card>
        <Card title="Packing checklist" icon={<Luggage className="h-5 w-5 text-[#ff7a00]"/>}><div className="grid gap-2 sm:grid-cols-2">{data.packing.map((item)=><label key={item.id} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-white/8 px-3 text-sm"><input type="checkbox" checked={item.packed} disabled={busy===item.id} onChange={(e)=>mutate({action:"toggle-packing",id:item.id,packed:e.target.checked},item.id)} className="h-4 w-4 accent-[#ff7a00]"/><span className={item.packed?"text-white/40 line-through":""}>{item.label}</span></label>)}</div></Card>
        <Card title="Budget tracker" icon={<CircleDollarSign className="h-5 w-5 text-[#ff7a00]"/>}><div className="mb-4 grid grid-cols-3 gap-2 text-center text-xs"><div><strong className="block text-base">{money(data.budget.planned,data.budget.currency)}</strong>Planned</div><div><strong className="block text-base">{money(data.budget.spent,data.budget.currency)}</strong>Spent</div><div><strong className={data.budget.remaining<0?"block text-base text-red-300":"block text-base text-emerald-300"}>{money(data.budget.remaining,data.budget.currency)}</strong>Remaining</div></div><form onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate({action:"set-budget",amount:Number(f.get("amount")),currency:f.get("currency")},"budget")}} className="flex gap-2"><input name="amount" type="number" min="0" step="1" defaultValue={data.budget.planned} className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 text-sm"/><input name="currency" defaultValue={data.budget.currency} maxLength={3} className="w-20 rounded-lg border border-white/10 bg-black/20 px-3 text-sm uppercase"/><button className="min-h-11 rounded-lg bg-[#ff7a00] px-4 text-xs font-bold">Save</button></form><form onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate({action:"add-expense",label:f.get("label"),category:"trip",amount:Number(f.get("amount")),currency:data.budget.currency},"expense");e.currentTarget.reset()}} className="mt-3 flex gap-2"><input name="label" required placeholder="Expense" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 text-sm"/><input name="amount" required type="number" min="0.01" step="0.01" placeholder="Amount" className="w-28 rounded-lg border border-white/10 bg-black/20 px-3 text-sm"/><button className="min-h-11 rounded-lg border border-[#ff7a00]/45 px-4 text-xs font-bold text-[#ffae64]">Add</button></form></Card>
        <Card title="In-app reminders" icon={<Bell className="h-5 w-5 text-[#ff7a00]"/>}><form onSubmit={addReminder} className="space-y-3"><input name="title" required placeholder="Reminder title" className="min-h-11 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm"/><input name="when" required type="datetime-local" className="min-h-11 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm"/><button disabled={busy==="reminder"} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#ff7a00] text-sm font-bold"><CalendarClock className="h-4 w-4"/>Save reminder</button><Link href={`/profile/bookings-reminders?tripId=${data.trip.id}`} className="block text-center text-xs text-[#ffae64]">View all reminders</Link></form></Card>
      </div>
    </div>
  </main>;
}
