"use client";

import Image from "next/image";
import Link from "next/link";
import { CalendarDays, ChevronRight, Heart, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const monthCopy = ["New Year Adventures", "Winter Wonders", "Spring Getaways", "Bloom & Explore", "Perfect Weather", "Beach Season", "Summer Escapes", "Peak Adventures", "Less Crowds, Better Prices", "Autumn Highlights", "Hidden Gems", "Festive Season"];
const fallbackImages = ["/images/Vietnam Adventure.jpg", "/images/Paros.webp", "/images/Inca Jungle.jpg", "/images/Santorini.avif"];
type Item = { id: string; type: string; title: string; destination?: string | null; description?: string | null; subtitle?: string | null; image?: string | null; href: string; months: number[]; daysCount?: number; startingPrice?: string | null; discountBadge?: string | null; dateRange?: string | null; endDate?: string | Date | null };

function track(eventName: string, metadata: Record<string, unknown> = {}) {
  void fetch("/api/analytics/event", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ eventName, category: "calendar", pagePath: "/profile/calendar", metadata }) });
}

export default function ProfileCalendar({ data, preference, wishlistItems = [] }: { data: { items?: Item[] }; preference?: any; wishlistItems?: any[] }) {
  const items = Array.isArray(data?.items) ? data.items : [];
  const initialDismissed = Array.isArray(preference?.metadata?.calendarDismissed) ? preference.metadata.calendarDismissed : [];
  const [selectedMonth, setSelectedMonth] = useState<number | null>(null);
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const [dismissed, setDismissed] = useState<string[]>(initialDismissed);
  const [saved, setSaved] = useState<string[]>(wishlistItems.map((item) => { const metadata = item?.metadata || {}; return metadata.sourceId && metadata.contentType ? `${metadata.contentType}:${metadata.sourceId}` : null; }).filter(Boolean));
  const [toast, setToast] = useState("");
  const visible = useMemo(() => items.filter((item) => !dismissed.includes(`${item.type}:${item.id}`) && (selectedMonth === null || item.months.includes(selectedMonth)) && (filter === "all" || item.type === filter) && (!query.trim() || `${item.title} ${item.destination || ""} ${item.description || ""} ${months.filter((_, index) => item.months.includes(index)).join(" ")}`.toLowerCase().includes(query.toLowerCase()))), [items, dismissed, selectedMonth, filter, query]);
  const perMonth = useMemo(() => months.map((_, month) => items.filter((item) => item.months.includes(month))), [items]);
  useEffect(() => { track("calendar_view", { publishedItems: items.length }); }, [items.length]);

  async function save(item: Item) {
    const key = `${item.type}:${item.id}`; if (saved.includes(key)) return;
    const itemType = item.type === "ready_plan" ? "ready_plan" : item.type === "destination" ? "destination" : "other";
    const response = await fetch("/api/profile/wishlist", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ itemType, title: item.title, destination: item.destination || null, imageUrl: item.image || null, href: item.href, metadata: { sourceId: item.id, source: "calendar", contentType: item.type } }) });
    if (response.ok) { setSaved((value) => [...value, key]); setToast("Saved to your favourites"); track("calendar_item_saved", { itemId: item.id, contentType: item.type, month: selectedMonth === null ? null : months[selectedMonth] }); }
    else setToast("This item could not be saved right now.");
  }

  async function persistDismissals(next: string[]) {
    const body = { travelStyles: preference?.travelStyles || [], preferredRegions: preference?.preferredRegions || [], mealPreferences: preference?.mealPreferences || [], preferredBudgetMin: preference?.preferredBudgetMin ?? null, preferredBudgetMax: preference?.preferredBudgetMax ?? null, preferredCurrency: preference?.preferredCurrency ?? null, hotelPreference: preference?.hotelPreference ?? null, preferredTransportation: preference?.preferredTransportation ?? null, activityIntensity: preference?.activityIntensity ?? null, typicalTripDuration: preference?.typicalTripDuration ?? null, accessibilityRequirements: preference?.accessibilityRequirements ?? null, metadata: { ...(preference?.metadata || {}), calendarDismissed: next, calendarDismissedAt: new Date().toISOString() } };
    await fetch("/api/profile/preferences", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  }

  function dismiss(item: Item) { const key = `${item.type}:${item.id}`; const next = [...dismissed, key]; setDismissed(next); setToast("Removed from your recommendations. Undo"); void persistDismissals(next); track("calendar_item_dismissed", { itemId: item.id, contentType: item.type }); }
  function undo() { const next = dismissed.slice(0, -1); setDismissed(next); setToast("Restored"); void persistDismissals(next); track("calendar_item_restored"); }

  return <div className="relative -mx-3 -mt-5 overflow-hidden px-3 pb-8 sm:-mx-5 sm:-mt-7 sm:px-5 lg:-mx-8 lg:-mt-8 lg:px-8">
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[390px] sm:h-[330px]"><Image src="/images/Greece Blue Island Romance/santorini.jpg" alt="" fill priority className="object-cover" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#07111a]/90 via-[#07111a]/40 to-[#07111a]/10" /><div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-[#07111a]/90" /></div>
    <div className="relative pt-7">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#ff7a00]">— Your travel year</p><h1 className="mt-3 max-w-2xl text-4xl font-black leading-tight sm:text-5xl">A Year Full of <span className="text-[#ff7a00]">Possibilities</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/75 sm:text-lg">See the best times to travel, holidays, deals and plan your perfect year with Gene.</p></header><label className="flex min-h-12 w-full max-w-md items-center gap-3 rounded-full border border-white/15 bg-black/45 px-5 backdrop-blur-xl"><Search className="h-5 w-5 text-white/55" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search months, destinations or events..." className="min-w-0 flex-1 bg-transparent text-sm outline-none" />{query ? <button aria-label="Clear search" onClick={() => setQuery("")}><X className="h-4 w-4" /></button> : null}</label></div>
      <div className="mt-5 flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{[["all","All"],["destination","Best Time"],["ready_plan","Ready Plans"],["offer","Special Offers"],["event","Unique Events"]].map(([key,label]) => <button key={key} onClick={() => { setFilter(key); track("filter_used", { filter: key }); }} className={`min-h-11 shrink-0 rounded-xl border px-4 text-sm font-bold ${filter === key ? "border-[#ff7a00] bg-[#ff7a00]/14 text-[#ff9b43] shadow-[0_0_22px_rgba(255,122,0,.16)]" : "border-white/12 bg-black/30 text-white/70"}`}>{label}</button>)}</div>
      {selectedMonth === null ? <div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-[repeat(3,minmax(0,1fr))]">{months.map((month, index) => { const monthItems = perMonth[index]; const offers = monthItems.filter((item) => item.type === "offer").length; const image = monthItems.find((item) => item.image)?.image || fallbackImages[index % fallbackImages.length]; return <button key={month} onClick={() => { setSelectedMonth(index); track("month_view", { month }); }} className="group relative min-h-[190px] overflow-hidden rounded-2xl border border-white/15 text-left shadow-xl transition hover:border-[#ff7a00]/65"><Image src={image!} alt="" fill className="object-cover transition duration-500 group-hover:scale-105 motion-reduce:transition-none" sizes="(max-width:767px) 100vw, (max-width:1279px) 50vw, 33vw" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/38 to-black/5" /><div className="absolute inset-0 flex flex-col justify-between p-4"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[.16em]">{month.slice(0,3)}</span><span className="flex h-9 w-9 items-center justify-center rounded-full bg-black/35"><ChevronRight className="h-4 w-4" /></span></div><div><h2 className="text-2xl font-black">{month}</h2><p className="mt-1 text-sm text-white/82">{monthCopy[index]}</p><div className="mt-3 flex gap-4 text-xs text-white/78"><span>{monthItems.length} published items</span>{offers ? <span>{offers} {offers === 1 ? "offer" : "offers"}</span> : null}</div></div></div></button>; })}</div> : <MonthExperience month={selectedMonth} items={visible} onBack={() => setSelectedMonth(null)} onSave={save} onDismiss={dismiss} saved={saved} />}
      {selectedMonth === null ? <Highlights items={items.filter((item) => item.type === "event").slice(0, 8)} /> : null}
      <section className="relative mt-5 overflow-hidden rounded-2xl border border-[#ff7a00]/25 p-6 sm:p-8"><Image src="/bg/home-hero-bottom-optimized.jpg" alt="" fill className="object-cover opacity-55" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#07111a] via-[#07111a]/80 to-transparent" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">Not sure where to go?</h2><p className="mt-1 text-sm text-white/65">Get personalized recommendations based on your interests and budget.</p></div><Link href="/profile/create-plan" onClick={() => track("calendar_plan_started")} className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#ff7a00] px-6 text-sm font-bold shadow-[0_0_24px_rgba(255,122,0,.18)]">Create My Plan →</Link></div></section>
    </div>
    {toast ? <div role="status" className="fixed bottom-24 left-1/2 z-50 flex min-h-12 -translate-x-1/2 items-center gap-3 whitespace-nowrap rounded-full border border-[#ff7a00]/30 bg-[#0b1620]/96 px-5 text-sm shadow-2xl backdrop-blur-xl">{toast}{toast.includes("Undo") ? <button onClick={undo} className="font-black text-[#ff9b43]">Undo</button> : null}<button aria-label="Dismiss message" onClick={() => setToast("")}><X className="h-4 w-4 text-white/50" /></button></div> : null}
  </div>;
}

function MonthExperience({ month, items, onBack, onSave, onDismiss, saved }: any) {
  const groups = [["ready_plan","Ready Plans"],["destination","Best Destinations"],["offer","Special Offers"],["event","Unique Events"]];
  return <div className="mt-4"><button onClick={onBack} className="min-h-11 text-sm font-bold text-[#ff9b43]">← Back to the year</button><div className="mb-5"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff7a00]">{months[month]}</p><h2 className="mt-2 text-3xl font-black">{monthCopy[month]}</h2></div>{items.length ? <div className="space-y-6">{groups.map(([type,title]) => { const section = items.filter((item: Item) => item.type === type); return section.length ? <section key={type}><h3 className="mb-3 text-lg font-black">{title}</h3><div className="flex snap-x gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{section.map((item: Item) => { const key = `${item.type}:${item.id}`; return <article key={key} className="relative min-w-[82vw] max-w-[340px] snap-start overflow-hidden rounded-2xl border border-white/12 bg-[#0d1720]/90 sm:min-w-[300px]"><div className="relative h-40"><Image src={item.image || fallbackImages[month % fallbackImages.length]} alt="" fill className="object-cover" sizes="340px" /><div className="absolute inset-0 bg-gradient-to-t from-[#0d1720] to-transparent" /></div><div className="p-4"><span className="text-[10px] font-black uppercase tracking-[.16em] text-[#ff9b43]">{item.type.replace("_"," ")}</span><h4 className="mt-1 text-lg font-black">{item.title}</h4>{item.destination ? <p className="mt-1 text-xs text-white/52">{item.destination}</p> : null}<div className="mt-4 flex items-center gap-2"><Link href={item.href} onClick={() => track("calendar_item_open", { itemId: item.id, contentType: item.type, month: months[month] })} className="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl bg-[#ff7a00] text-sm font-black">Explore</Link><button aria-label={`Save ${item.title}`} onClick={() => onSave(item)} className={`flex h-11 w-11 items-center justify-center rounded-xl border ${saved.includes(key) ? "border-[#ff7a00] bg-[#ff7a00]/15 text-[#ff7a00]" : "border-white/15 text-white/70"}`}><Heart className={`h-5 w-5 ${saved.includes(key) ? "fill-current" : ""}`} /></button><button aria-label={`Not for me: ${item.title}`} onClick={() => onDismiss(item)} className="flex h-11 w-11 items-center justify-center rounded-xl border border-white/15 text-white/50"><X className="h-5 w-5" /></button></div></div></article>; })}</div></section> : null; })}</div> : <div className="rounded-2xl border border-dashed border-white/15 bg-white/[0.035] p-10 text-center"><CalendarDays className="mx-auto h-8 w-8 text-[#ff7a00]" /><h3 className="mt-4 text-xl font-black">More possibilities are coming.</h3><Link href="/destinations" className="mt-5 inline-flex min-h-11 items-center rounded-xl border border-[#ff7a00] px-5 text-sm font-bold">Explore Destinations →</Link></div>}</div>;
}

function Highlights({ items }: { items: Item[] }) { if (!items.length) return null; return <section className="mt-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Upcoming Highlights</h2><p className="text-xs text-white/50">Real published events from Gene</p></div><Link href="/events" className="text-sm font-bold text-[#ff9b43]">View all</Link></div><div className="mt-3 flex snap-x gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{items.map((item) => <Link key={item.id} href={item.href} onClick={() => track("event_opened", { itemId: item.id })} className="flex min-w-[270px] snap-start items-center gap-3 rounded-2xl border border-white/12 bg-[#0d1720]/86 p-3"><div className="relative h-16 w-20 shrink-0 overflow-hidden rounded-xl"><Image src={item.image || fallbackImages[3]} alt="" fill className="object-cover" sizes="80px" /></div><div className="min-w-0 flex-1"><p className="truncate font-bold">{item.title}</p><p className="mt-1 truncate text-xs text-white/50">{item.destination || item.dateRange || "Gene event"}</p></div><ChevronRight className="h-5 w-5 text-white/50" /></Link>)}</div></section>; }
