import type {
  ActivityRecommendation,
  CarRecommendation,
  FlightRecommendation,
  HotelRecommendation,
  RestaurantRecommendation,
  TransportRecommendation,
} from "@/lib/recommendation/types";

export const mockHotels: HotelRecommendation[] = [
  {
    id: "hotel-1",
    name: "Le Grand Hotel",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    provider: "Booking.com",
    sourceBadge: "Booking",
    aiReason: "Best value in a central zone with smooth access to the city’s main landmarks.",
    badge: "Best Value",
    confidenceScore: 91,
    freshnessLabel: "Price refreshed 12 min ago",
    fitTags: ["Low walking", "Couple fit", "Central"],
    area: "Paris Centre",
    locationLabel: "11 min from core attractions",
    rating: 4.8,
    reviewsLabel: "4.8 • 1.9k reviews",
    nightlyPrice: 240,
    amenities: ["Breakfast", "Fast Wi-Fi", "City View"],
    deepLink: "#",
  },
  {
    id: "hotel-2",
    name: "Maison Lumiere",
    imageUrl: "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=1200&q=80",
    provider: "Trip.com",
    sourceBadge: "Trip",
    aiReason: "Best for couples wanting a quieter district and stronger evening ambiance.",
    badge: "Romantic",
    confidenceScore: 88,
    freshnessLabel: "Price refreshed 28 min ago",
    fitTags: ["Couples", "Quiet zone", "Premium"],
    area: "Seine Riverside",
    locationLabel: "Riverfront quarter",
    rating: 4.7,
    reviewsLabel: "4.7 • 1.2k reviews",
    nightlyPrice: 285,
    amenities: ["Riverside view", "Concierge", "Late check-in"],
    deepLink: "#",
  },
  {
    id: "hotel-3",
    name: "Aurora Residence",
    imageUrl: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80",
    provider: "Hotels Partner",
    sourceBadge: "Hotel API",
    aiReason: "Balanced luxury and comfort with roomier layouts and lower transition stress.",
    badge: "Comfort",
    confidenceScore: 86,
    freshnessLabel: "Availability checked today",
    fitTags: ["Family-safe", "Spacious", "Comfort"],
    area: "Louvre District",
    locationLabel: "Short transfer to museum cluster",
    rating: 4.6,
    reviewsLabel: "4.6 • 860 reviews",
    nightlyPrice: 315,
    amenities: ["Suite rooms", "Lounge", "Spa"],
    deepLink: "#",
  },
];

export const mockFlights: FlightRecommendation[] = [
  {
    id: "flight-1",
    name: "Arrive CDG - Air France",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80",
    provider: "Flight Affiliate",
    sourceBadge: "Amadeus",
    aiReason: "Best timing for a smooth hotel check-in and lower first-day fatigue.",
    badge: "Best Timing",
    confidenceScore: 90,
    freshnessLabel: "Fare refreshed 9 min ago",
    fitTags: ["Direct", "Arrival fit", "Low stress"],
    airline: "Air France",
    route: "Cairo → Paris",
    locationLabel: "CDG arrival",
    departureTime: "09:30",
    arrivalTime: "12:15",
    duration: "4h 45m",
    stops: 0,
    fare: 350,
    deepLink: "#",
  },
  {
    id: "flight-2",
    name: "Arrive CDG - Transavia",
    imageUrl: "https://images.unsplash.com/photo-1540339832862-474599807836?auto=format&fit=crop&w=1200&q=80",
    provider: "Flight Affiliate",
    sourceBadge: "Skyscanner",
    aiReason: "Best budget-preserving route if you want more room for dining and activities.",
    badge: "Budget Saver",
    confidenceScore: 84,
    freshnessLabel: "Fare refreshed 17 min ago",
    fitTags: ["Budget", "Direct", "Early arrival"],
    airline: "Transavia",
    route: "Cairo → Paris",
    locationLabel: "CDG arrival",
    departureTime: "08:10",
    arrivalTime: "11:05",
    duration: "4h 55m",
    stops: 0,
    fare: 295,
    deepLink: "#",
  },
  {
    id: "flight-3",
    name: "Arrive CDG - Emirates",
    imageUrl: "https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80",
    provider: "Flight Affiliate",
    sourceBadge: "Trip",
    aiReason: "Premium comfort if reducing travel fatigue matters more than absolute price.",
    badge: "Luxury",
    confidenceScore: 82,
    freshnessLabel: "Fare refreshed 23 min ago",
    fitTags: ["Comfort", "Premium", "Low stress"],
    airline: "Emirates",
    route: "Cairo → Paris",
    locationLabel: "CDG arrival",
    departureTime: "11:00",
    arrivalTime: "13:50",
    duration: "4h 50m",
    stops: 0,
    fare: 430,
    deepLink: "#",
  },
];

export const mockActivities: ActivityRecommendation[] = [
  {
    id: "activity-1",
    name: "Louvre Museum Tour",
    imageUrl: "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=1200&q=80",
    provider: "Viator",
    sourceBadge: "Viator",
    aiReason: "Strong cultural anchor with indoor protection and clean timing on a full day.",
    badge: "Iconic",
    confidenceScore: 92,
    freshnessLabel: "Opening hours checked today",
    fitTags: ["Indoor", "Culture", "Low weather risk"],
    locationLabel: "Louvre area",
    duration: "2h 30m",
    price: 75,
    categoryLabel: "Museum",
    bestTimeOfDay: "Morning",
    weatherFit: "Excellent on warm or rainy days",
    deepLink: "#",
  },
  {
    id: "activity-2",
    name: "Seine Sunset Cruise",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    provider: "Viator",
    sourceBadge: "Viator",
    aiReason: "Best romantic evening moment and ideal visual payoff for a lighter day.",
    badge: "Romantic",
    confidenceScore: 89,
    freshnessLabel: "Suitability updated now",
    fitTags: ["Evening", "Couple fit", "Scenic"],
    locationLabel: "Seine riverside",
    duration: "1h 45m",
    price: 68,
    categoryLabel: "Cruise",
    bestTimeOfDay: "Evening",
    weatherFit: "Best in clear or mild weather",
    deepLink: "#",
  },
  {
    id: "activity-3",
    name: "Montmartre Walk & Cafe Stop",
    imageUrl: "https://images.unsplash.com/photo-1502602898530-47d6b1a5b8f5?auto=format&fit=crop&w=1200&q=80",
    provider: "GetYourGuide",
    sourceBadge: "GYG",
    aiReason: "Great fit for travelers who want atmosphere without the density of heavy museum scheduling.",
    badge: "Local Pick",
    confidenceScore: 85,
    freshnessLabel: "Availability checked today",
    fitTags: ["Local vibe", "Cafe stop", "Afternoon"],
    locationLabel: "Montmartre",
    duration: "3h",
    price: 45,
    categoryLabel: "Walking Tour",
    bestTimeOfDay: "Afternoon",
    weatherFit: "Best in mild, dry weather",
    deepLink: "#",
  },
  {
    id: "activity-4",
    name: "Covered Passage Food Crawl",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
    provider: "Viator",
    sourceBadge: "Viator",
    aiReason: "Strong foodie option with indoor shelter and good pacing between major landmarks.",
    badge: "Foodie",
    confidenceScore: 87,
    freshnessLabel: "Updated this morning",
    fitTags: ["Indoor", "Foodie", "Low walking"],
    locationLabel: "Opera district",
    duration: "2h",
    price: 58,
    categoryLabel: "Food Tour",
    bestTimeOfDay: "Midday",
    weatherFit: "Excellent in rain or peak heat",
    deepLink: "#",
  },
];

export const mockRestaurants: RestaurantRecommendation[] = [
  {
    id: "restaurant-1",
    name: "Atelier des Saveurs",
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
    provider: "Tripadvisor",
    sourceBadge: "Dining",
    aiReason: "Best dinner anchor near your activity cluster with a polished but relaxed atmosphere.",
    badge: "Dinner Pick",
    confidenceScore: 88,
    freshnessLabel: "Hours checked today",
    fitTags: ["Dinner", "Couple fit", "Low detour"],
    locationLabel: "Near central activity zone",
    cuisine: "French",
    mealWindow: "Dinner",
    pricePerPerson: 48,
    rating: 4.7,
    deepLink: "#",
  },
  {
    id: "restaurant-2",
    name: "Cafe Lumiere",
    imageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
    provider: "Tripadvisor",
    sourceBadge: "Dining",
    aiReason: "Good midday stop with lighter pacing and easy timing around museum-heavy days.",
    badge: "Lunch Pick",
    confidenceScore: 82,
    freshnessLabel: "Hours checked today",
    fitTags: ["Lunch", "Cafe", "Low stress"],
    locationLabel: "Close to museum corridor",
    cuisine: "Cafe",
    mealWindow: "Lunch",
    pricePerPerson: 24,
    rating: 4.5,
    deepLink: "#",
  },
];

export const mockTransports: TransportRecommendation[] = [
  {
    id: "transport-1",
    name: "Private Airport Transfer",
    imageUrl: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1200&q=80",
    provider: "Transfer Partner",
    sourceBadge: "Transfer",
    aiReason: "Lowest friction arrival option after landing, especially with luggage or family travel.",
    badge: "Low Stress",
    confidenceScore: 90,
    freshnessLabel: "Checked now",
    fitTags: ["Arrival", "Comfort", "Low walking"],
    locationLabel: "Airport to hotel",
    transportType: "Private driver",
    duration: "45 min",
    cost: 80,
    costLabel: "$80 / ride",
    deepLink: "#",
  },
  {
    id: "transport-2",
    name: "Paris Metro Pass",
    imageUrl: "https://images.unsplash.com/photo-1517148815978-75f6acaaf32c?auto=format&fit=crop&w=1200&q=80",
    provider: "Transit Partner",
    sourceBadge: "Transit",
    aiReason: "Best budget option for flexible movement if you are comfortable with denser city flow.",
    badge: "Saver",
    confidenceScore: 79,
    freshnessLabel: "Checked this morning",
    fitTags: ["Budget", "City", "Flexible"],
    locationLabel: "City-wide access",
    transportType: "Metro pass",
    duration: "3 days",
    cost: 25,
    costLabel: "$25 / 3 days",
    deepLink: "#",
  },
  {
    id: "transport-3",
    name: "Executive Rail Transfer",
    imageUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1200&q=80",
    provider: "Rail Europe",
    sourceBadge: "Rail",
    aiReason: "Balanced speed and predictability for travelers who want cleaner timing than road traffic.",
    badge: "Fast",
    confidenceScore: 84,
    freshnessLabel: "Schedule checked today",
    fitTags: ["Fast", "Predictable", "Low traffic risk"],
    locationLabel: "Airport rail corridor",
    transportType: "Train",
    duration: "35 min",
    cost: 45,
    costLabel: "$45 total",
    deepLink: "#",
  },
];

export const mockCars: CarRecommendation[] = [
  {
    id: "car-1",
    name: "Fiat 500",
    imageUrl: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1200&q=80",
    provider: "Rentalcars",
    sourceBadge: "Car Hire",
    aiReason: "Best city-friendly option when you want flexibility without overspending on parking and fuel.",
    badge: "Compact",
    confidenceScore: 78,
    freshnessLabel: "Fleet checked today",
    fitTags: ["Compact", "City", "Budget"],
    locationLabel: "Airport pickup",
    carType: "Compact",
    seats: 4,
    luggage: 2,
    transmission: "Automatic",
    dailyPrice: 55,
    deepLink: "#",
  },
  {
    id: "car-2",
    name: "Peugeot 3008",
    imageUrl: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80",
    provider: "Rentalcars",
    sourceBadge: "Car Hire",
    aiReason: "Best overall comfort and storage if day trips or family logistics matter.",
    badge: "Top Match",
    confidenceScore: 86,
    freshnessLabel: "Fleet checked today",
    fitTags: ["Family", "Comfort", "Flexible"],
    locationLabel: "Airport pickup",
    carType: "SUV",
    seats: 5,
    luggage: 4,
    transmission: "Automatic",
    dailyPrice: 95,
    deepLink: "#",
  },
  {
    id: "car-3",
    name: "Mercedes C Class",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    provider: "Luxury Cars",
    sourceBadge: "Car Hire",
    aiReason: "Premium mobility feel if the trip is comfort-first and budget is less constrained.",
    badge: "Luxury",
    confidenceScore: 81,
    freshnessLabel: "Fleet checked today",
    fitTags: ["Luxury", "Comfort", "Business"],
    locationLabel: "Airport pickup",
    carType: "Sedan",
    seats: 5,
    luggage: 3,
    transmission: "Automatic",
    dailyPrice: 145,
    deepLink: "#",
  },
];
