-- Additive compatibility migration for customer profile account reads.
-- This migration only creates missing tables/columns with safe defaults.

DO $$
BEGIN
  CREATE TYPE "PassStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELED', 'REFUNDED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "passes" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT,
  "tier" TEXT NOT NULL DEFAULT 'starter',
  "status" "PassStatus" NOT NULL DEFAULT 'ACTIVE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "tier" TEXT NOT NULL DEFAULT 'starter';
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "status" "PassStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "customerEmail" TEXT;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "paymentId" TEXT;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "planType" TEXT;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "tierActionsTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "tierActionsUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "mainCreditsTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "mainCreditsUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "editCreditsTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "editCreditsUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "whatIfFreeTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "whatIfFreeUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "chatMessagesTotal" INTEGER;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "chatMessagesUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "expertReviewTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "expertReviewUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "meta" JSONB;
ALTER TABLE "passes" ADD COLUMN IF NOT EXISTS "profileId" TEXT;

CREATE INDEX IF NOT EXISTS "passes_userId_idx" ON "passes"("userId");
CREATE INDEX IF NOT EXISTS "passes_profileId_idx" ON "passes"("profileId");

CREATE TABLE IF NOT EXISTS "payments" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT,
  "customerEmail" TEXT,
  "provider" TEXT NOT NULL DEFAULT 'unknown',
  "planType" TEXT NOT NULL DEFAULT 'starter',
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "customerEmail" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "provider" TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "planType" TEXT NOT NULL DEFAULT 'starter';
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "providerCustomerId" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "providerOrderId" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "providerCheckoutId" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "providerPaymentId" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "subscriptionId" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "currency" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "meta" JSONB;

CREATE INDEX IF NOT EXISTS "payments_userId_idx" ON "payments"("userId");
CREATE INDEX IF NOT EXISTS "payments_status_idx" ON "payments"("status");

CREATE TABLE IF NOT EXISTS "deals" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT NOT NULL,
  "meta" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
